### ISSUE TITLE
make bootstrap idempotent 

### ISSUE THREAD

**Issue by DanielMueller1309** [DanielMueller1309/ansible#7]
```
TASK [mgrote.set_apt_sources : apt_update] ****************************************************************************
changed: [pihole]
```
siehe folgenden code:
```yml
 - name: apt_update # noqa 503 503
    become: true
    apt:
      update_cache: yes
    #when: copy_src.changed
```
unter:
https://github.com/DanielMueller1309/ansible/blob/ansible_pihole/ansible_home/roles/mgrote.set_apt_sources/tasks/main.yml#:~:text=-%20name%3A%20apt_update%20%23%20noqa%20503%20503
