### ISSUE TITLE
tmux root bashrc

### ISSUE THREAD

**Issue by DanielMueller1309** [DanielMueller1309/ansible#8]
ansible sagt:
```yml
failed: [192.168.178.10] (item={'username': 'root', 'tmux_allow': True, 'tmux_downloadpath': 'https://raw.githubusercontent.com/DanielMueller1309/linux/master/Programme/tmux/.tmux.conf', 'tmux_conf_destinati
on': '/home/.tmux.conf', 'tmux_bashrc_destination': '/home/.bashrc', 'tmux_standardsession_name': 'default'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "_diff_peek": null,
            "_original_basename": null,
            "access_time": null,
            "access_time_format": "%Y%m%d%H%M.%S",
            "attributes": null,
            "follow": true,
            "force": false,
            "group": null,
            "mode": null,
            "modification_time": null,
            "modification_time_format": "%Y%m%d%H%M.%S",
            "owner": null,
            "path": "/home/.bashrc",
            "recurse": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "file",
            "unsafe_writes": false
        }
    },
    "item": {
        "tmux_allow": true,
        "tmux_bashrc_destination": "/home/.bashrc",
        "tmux_conf_destination": "/home/.tmux.conf",
        "tmux_downloadpath": "https://raw.githubusercontent.com/DanielMueller1309/linux/master/Programme/tmux/.tmux.conf",
        "tmux_standardsession_name": "default",
        "username": "root"
    },
    "msg": "file (/home/.bashrc) is absent, cannot continue",
    "path": "/home/.bashrc",
    "state": "absent"
}

```
